version: '3'

volumes:
  db:

services:
  autogpt:
    build:
      context: .
      args:
        NEXTAUTH_URL: http://localhost:3000
        DATABASE_URL: file:../db/db.sqlite
        SKIP_ENV_VALIDATION: 1 # omit this property to enable schema validation for the environment variables
    container_name: autogpt
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY} # openai api key
      NEXT_PUBLIC_WEB_SEARCH_ENABLED: ${NEXT_PUBLIC_WEB_SEARCH_ENABLED} # enable web search
      SERP_API_KEY: ${SERP_API_KEY} # serp api key
    ports:
      - 3000:3000
    volumes:
      - db:/app/db
    restart: unless-stopped

  platform:
    container_name: platform
    build:
      context: ./platform
      target: prod
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: db
      REWORKD_PLATFORM_DB_PORT: "3306"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    restart: always
    build:
      context: ./db
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_PASSWORD: "reworkd_platform"
      MYSQL_ROOT_PASSWORD: "reworkd_platform"
    volumes:
      - db_data:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

  volumes:
    db_data:
